version: "3.9"
services:
  node1:  
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=0  
    ports:
      - "5001:5000"

  node2:  
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=1
    ports:
      - "5002:5000"

  node3:  
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=2
    ports:
      - "5003:5000"

  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STARTUP_SCRIPT: load-balancer.py
    ports:
      - "6000:6000"